# Generated by Django 4.0 on 2023-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_car_id_alter_cardealer_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_rating',
            name='car',
        ),
        migrations.RemoveField(
            model_name='car_rating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='car_rating',
            name='review',
        ),
        migrations.AddField(
            model_name='car_rating',
            name='registeration_number',
            field=models.CharField(default='TN', max_length=10),
            preserve_default=False,
        ),
    ]
